

/******************************************************************************



        !  DO NOT EDIT THIS FILE AS IT MAY BE OVERWRITTEN BY
        THE DESIGNER RESULTING IN YOUR CHANGES BEING LOST  !

DISTRIBUTION.  This software may NOT be distributed to a third party without
prior written approval of the copyright holder. Please see the FFT Designer
End User Licence Agreement for details about distribution in object-code form.

DISCLAIMER.  This software is provided "AS IS", without express or implied
warranty.  In no event shall the copyright holder, author(s) or provider(s)
of this software be held liable for any damages arising from its use.

        FFTLength ................................ 1024
        WindowType ............................... Kaiser
        WindowLoss (dB) .......................... 7.91
        WindowAlpha .............................. 3
        Language ................................. Standard ANSI C
        Algorithm ................................ Integer (16 Bit)
        Use Shift Division ....................... False

******************************************************************************/

#include "duFFT.h"

// export lookup tables

extern const duFFT_Workspace_t duFFT_SampledR[];
extern const duFFT_Workspace_t duFFT_SampledI[];
extern const duFFT_Workspace_t duFFT_WindowedR[];
extern const duFFT_Workspace_t duFFT_WindowedI[];
extern const duFFT_Workspace_t duFFT_TransformedR[];
extern const duFFT_Workspace_t duFFT_TransformedI[];

// export test methods

void duFFT_TestHarnessLoadComplex(const duFFT_Workspace_t * table_pointer_r, const duFFT_Workspace_t * table_pointer_i);
void duFFT_TestHarnessLoadWindowed(void);
void duFFT_TestHarnessLoadSampled(void);
int duFFT_TestHarnessCompareComplex(const duFFT_Workspace_t * table_pointer_r, const duFFT_Workspace_t * table_pointer_i);
int duFFT_TestHarnessCompareWindowed(void);
int duFFT_TestHarnessCompareTransformed(void);
