

/******************************************************************************



        !  DO NOT EDIT THIS FILE AS IT MAY BE OVERWRITTEN BY
        THE DESIGNER RESULTING IN YOUR CHANGES BEING LOST  !

DISTRIBUTION.  This software may NOT be distributed to a third party without
prior written approval of the copyright holder. Please see the FFT Designer
End User Licence Agreement for details about distribution in object-code form.

DISCLAIMER.  This software is provided "AS IS", without express or implied
warranty.  In no event shall the copyright holder, author(s) or provider(s)
of this software be held liable for any damages arising from its use.

        FFTLength ................................ 1024
        WindowType ............................... Kaiser
        WindowLoss (dB) .......................... 7.91
        WindowAlpha .............................. 3
        Language ................................. Standard ANSI C
        Algorithm ................................ Integer (16 Bit)
        Use Shift Division ....................... False

******************************************************************************/

#include "duFFT_Tables.h"
#include "duFFT_Include.h"

#define duFFT_INPUT_LENGTH	1024
#define duFFT_LOG2BASE2OFN	10
#define duFFT_WINDOW_LOSS_DB	7.91

extern duFFT_Workspace_t duFFT_ResultR[];
extern duFFT_Workspace_t duFFT_ResultI[];

void duFFT_Sample(duFFT_Workspace_t * input_buffer);
void duFFT_Window(void);
void duFFT_Reorder(void);
void duFFT_Transform(void);
void duFFT_CalculateDft(duFFT_Workspace_t * input_buffer);
void duFFT_Init(duFFT_Workspace_t * input_buffer_start, int input_buffer_length);
